# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MajiPay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MajiPay
  pod 'Alamofire', '~> 4.4'
  pod 'GoogleMaps', '~> 2.2'
  pod 'RappleProgressHUD'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  target 'MajiPayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MajiPayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
